// <auto-generated />
using DataLayer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations.AuctionDb
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("DataLayer.Entities.Auction.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ImageFileName = "7a9ae808-5cba-4aca-a548-9e5497dcf520.png",
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 2L,
                            ImageFileName = "d9b53dda-f99b-4569-a294-3807faefec49.png",
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = 3L,
                            ImageFileName = "f2647ff0-3530-4e7a-a009-a2957e19db6d.png",
                            Name = "Tablets"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Auction.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BidderEmail")
                        .HasColumnType("longtext");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SellerPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Description = "M: 1201",
                            ImageFileName = "7b739908-b892-4961-80cd-46a80d45b1e9.png",
                            Name = "Monitor",
                            Price = 500000,
                            SellerPrice = 500000
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Description = "S: 1301",
                            ImageFileName = "0cbc67c4-37e1-4046-9068-5fd6b5eb8410.png",
                            Name = "Smartphone",
                            Price = 300000,
                            SellerPrice = 300000
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            Description = "T: 1401",
                            ImageFileName = "00c24b2c-3117-4e82-8161-c877e8550b09.png",
                            Name = "Tablet",
                            Price = 400000,
                            SellerPrice = 400000
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1L,
                            Description = "M: 1202",
                            ImageFileName = "9d3ace22-2a12-4fe8-8998-a4464aff13f6.png",
                            Name = "Monitor",
                            Price = 500000,
                            SellerPrice = 500000
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 2L,
                            Description = "S: 1302",
                            ImageFileName = "2f4e71c1-b99f-41f5-a4e3-04eae3998cf4.png",
                            Name = "Smartphone",
                            Price = 300000,
                            SellerPrice = 300000
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 3L,
                            Description = "T: 1402",
                            ImageFileName = "1a710d16-e145-4eff-9df3-8422e917e582.png",
                            Name = "Tablet",
                            Price = 400000,
                            SellerPrice = 400000
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 1L,
                            Description = "M: 1203",
                            ImageFileName = "578dd49b-b719-40bb-a562-31f47f98c68b.png",
                            Name = "Monitor",
                            Price = 500000,
                            SellerPrice = 500000
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 2L,
                            Description = "S: 1303",
                            ImageFileName = "7b5554f9-8eee-4d7f-95ed-943b31ddfcfd.png",
                            Name = "Smartphone",
                            Price = 300000,
                            SellerPrice = 300000
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 3L,
                            Description = "T: 1403",
                            ImageFileName = "7eb25132-59a7-4ce8-95a4-fb9239200147.png",
                            Name = "Tablet",
                            Price = 400000,
                            SellerPrice = 400000
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 1L,
                            Description = "M: 1204",
                            ImageFileName = "9049d1b8-2d9a-40f7-b38f-b5d185d4b547.png",
                            Name = "Monitor",
                            Price = 500000,
                            SellerPrice = 500000
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 2L,
                            Description = "S: 1304",
                            ImageFileName = "56c9618e-fb42-42d3-bdc3-eeec29f28e72.png",
                            Name = "Smartphone",
                            Price = 300000,
                            SellerPrice = 300000
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 3L,
                            Description = "T: 1404",
                            ImageFileName = "babeb68c-ff0b-4b24-b237-8c57c4773924.png",
                            Name = "Tablet",
                            Price = 400000,
                            SellerPrice = 400000
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 1L,
                            Description = "M: 1205",
                            ImageFileName = "99145066-ab8a-409f-88a9-6096ce62d6f6.png",
                            Name = "Monitor",
                            Price = 500000,
                            SellerPrice = 500000
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 2L,
                            Description = "S: 1305",
                            ImageFileName = "60917223-b1cb-47a0-a167-b229d2bca970.png",
                            Name = "Smartphone",
                            Price = 300000,
                            SellerPrice = 300000
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 3L,
                            Description = "T: 1405",
                            ImageFileName = "d84d23da-f2ca-4271-8a49-b4d0b474d549.png",
                            Name = "Tablet",
                            Price = 400000,
                            SellerPrice = 400000
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Auction.Product", b =>
                {
                    b.HasOne("DataLayer.Entities.Auction.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataLayer.Entities.Auction.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
